// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Tmp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Tmp.Data.Entity
{
    // ProjectInfo
    public partial class ProjectInfoConfiguration : EntityTypeConfiguration<ProjectInfo>
    {
        public ProjectInfoConfiguration()
            : this("dbo")
        {
        }
 
        public ProjectInfoConfiguration(string schema)
        {
            ToTable(schema + ".ProjectInfo");
            HasKey(x => x.ID);

            Property(x => x.ID).HasColumnName("ID").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.ProjectName).HasColumnName("ProjectName").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.ProjectType).HasColumnName("ProjectType").IsOptional().HasColumnType("int");
            Property(x => x.AccountID).HasColumnName("AccountID").IsOptional().HasColumnType("uniqueidentifier");
            Property(x => x.ProjectAddress).HasColumnName("ProjectAddress").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.ProjectSbeummary).HasColumnName("ProjectSbeummary").IsOptional().IsUnicode(false).HasColumnType("varchar");
            Property(x => x.StartTime).HasColumnName("StartTime").IsOptional().HasColumnType("date");
            Property(x => x.EndTime).HasColumnName("EndTime").IsOptional().HasColumnType("date");
            Property(x => x.CreateTime).HasColumnName("CreateTime").IsOptional().HasColumnType("datetime");
            Property(x => x.Remarks).HasColumnName("Remarks").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
