// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Tmp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Tmp.Data.Entity
{
    // ProjectInfo
    public partial class ProjectInfo: BaseEntity
    {

        ///<summary>
        /// 主键
        ///</summary>
        public Guid ID { get; set; } // ID (Primary key)

        ///<summary>
        /// 项目名称
        ///</summary>
        public string ProjectName { get; set; } // ProjectName

        ///<summary>
        /// 项目类型 （枚举类型）
        ///</summary>
        public int? ProjectType { get; set; } // ProjectType

        ///<summary>
        /// 负责人
        ///</summary>
        public Guid? AccountID { get; set; } // AccountID

        ///<summary>
        /// 项目地址
        ///</summary>
        public string ProjectAddress { get; set; } // ProjectAddress

        ///<summary>
        /// 项目简介
        ///</summary>
        public string ProjectSbeummary { get; set; } // ProjectSbeummary

        ///<summary>
        /// 项目开始日期
        ///</summary>
        public DateTime? StartTime { get; set; } // StartTime

        ///<summary>
        /// 项目结束时间
        ///</summary>
        public DateTime? EndTime { get; set; } // EndTime

        ///<summary>
        /// 记录创建时间
        ///</summary>
        public DateTime? CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 备注
        ///</summary>
        public string Remarks { get; set; } // Remarks
        
        public ProjectInfo()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
