// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Tmp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Tmp.Data.Entity
{
    // tbLOG_Account
    public partial class Account: BaseEntity
    {

        ///<summary>
        /// 全局唯一标识
        ///</summary>
        public Guid ID { get; set; } // ID (Primary key)

        ///<summary>
        /// 用户ID
        ///</summary>
        public string AccountID { get; set; } // AccountID

        ///<summary>
        /// 用户名称
        ///</summary>
        public string Name { get; set; } // Name

        ///<summary>
        /// 用户密码
        ///</summary>
        public string Password { get; set; } // Password

        ///<summary>
        /// 部门ID
        ///</summary>
        public short DepartmentsID { get; set; } // DepartmentsID

        ///<summary>
        /// 创建时间
        ///</summary>
        public DateTime AddTime { get; set; } // AddTime

        ///<summary>
        /// 编辑时间
        ///</summary>
        public DateTime EditTime { get; set; } // EditTime

        ///<summary>
        /// 头像
        ///</summary>
        public string Img { get; set; } // Img

        ///<summary>
        /// 是否启用
        ///</summary>
        public bool IsUse { get; set; } // IsUse
        
        public Account()
        {
            ID = System.Guid.NewGuid();
            DepartmentsID = 0;
            AddTime = System.DateTime.Now;
            EditTime = System.DateTime.Now;
            IsUse = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
