// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Tmp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Tmp.Data.Entity
{
    // BuildingModel
    public partial class BuildingModel: BaseEntity
    {
        public Guid ID { get; set; } // ID (Primary key)
        public Guid? ModelInfoID { get; set; } // ModelInfoID
        public string FilePath { get; set; } // FilePath
        public string FileName { get; set; } // FileName
        public string Description { get; set; } // Description
        public string ModelVersion { get; set; } // ModelVersion
        public DateTime? CreateTime { get; set; } // CreateTime
        
        public BuildingModel()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
