// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Tmp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Tmp.Data.Entity
{
    // tbLOG_ErrorInfo
    public partial class ErrorInfoConfiguration : EntityTypeConfiguration<ErrorInfo>
    {
        public ErrorInfoConfiguration()
            : this("dbo")
        {
        }
 
        public ErrorInfoConfiguration(string schema)
        {
            ToTable(schema + ".tbLOG_ErrorInfo");
            HasKey(x => x.ID);

            Property(x => x.ID).HasColumnName("ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.UID).HasColumnName("UID").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(200);
            Property(x => x.ErrorCode).HasColumnName("ErrorCode").IsRequired().HasColumnType("int");
            Property(x => x.ErrorMsg).HasColumnName("ErrorMsg").IsOptional().HasColumnType("nvarchar");
            Property(x => x.RunningTime).HasColumnName("RunningTime").IsRequired().HasColumnType("datetime");
            Property(x => x.ProgramID).HasColumnName("ProgramID").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(200);
            Property(x => x.Url).HasColumnName("Url").IsRequired().HasColumnType("nvarchar");
            Property(x => x.ExecSql).HasColumnName("ExecSql").IsRequired().HasColumnType("nvarchar");
            Property(x => x.StackTrace).HasColumnName("StackTrace").IsRequired().HasColumnType("nvarchar");
            Property(x => x.SolveBy).HasColumnName("SolveBy").IsRequired().HasColumnType("nvarchar");
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
