// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Tmp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Tmp.Data.Entity
{
    // FileModular
    public partial class FileModular: BaseEntity
    {
        public Guid FileModularID { get; set; } // FileModularID (Primary key)
        public string FileType { get; set; } // FileType
        public Guid? RefFIleID { get; set; } // Ref_FIleID
        public Guid? RefProjectID { get; set; } // Ref_ProjectID

        // Foreign keys
        public virtual FileMange FileMange { get; set; } // FileMange_FileModular_FileID
        
        public FileModular()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
