// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Tmp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Tmp.Data.Entity
{
    // FileMange
    public partial class FileMangeConfiguration : EntityTypeConfiguration<FileMange>
    {
        public FileMangeConfiguration()
            : this("dbo")
        {
        }
 
        public FileMangeConfiguration(string schema)
        {
            ToTable(schema + ".FileMange");
            HasKey(x => x.FileID);

            Property(x => x.FileID).HasColumnName("FileID").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.NameBefore).HasColumnName("NameBefore").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.NameNow).HasColumnName("NameNow").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.Date).HasColumnName("Date").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.Size).HasColumnName("Size").IsOptional().HasColumnType("decimal");
            Property(x => x.UserId).HasColumnName("UserId").IsOptional().HasColumnType("uniqueidentifier");
            Property(x => x.FileType).HasColumnName("FileType").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.FilePath).HasColumnName("FilePath").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.ProjectId).HasColumnName("ProjectId").IsOptional().HasColumnType("uniqueidentifier");
            Property(x => x.FileCategory).HasColumnName("FileCategory").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.FileExplain).HasColumnName("FileExplain").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.UserName).HasColumnName("UserName").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.ProjectName).HasColumnName("ProjectName").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
