// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Tmp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Tmp.Data.Entity
{
    // FileModular
    public partial class FileModularConfiguration : EntityTypeConfiguration<FileModular>
    {
        public FileModularConfiguration()
            : this("dbo")
        {
        }
 
        public FileModularConfiguration(string schema)
        {
            ToTable(schema + ".FileModular");
            HasKey(x => x.FileModularID);

            Property(x => x.FileModularID).HasColumnName("FileModularID").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.FileType).HasColumnName("FileType").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.RefFIleID).HasColumnName("Ref_FIleID").IsOptional().HasColumnType("uniqueidentifier");
            Property(x => x.RefProjectID).HasColumnName("Ref_ProjectID").IsOptional().HasColumnType("uniqueidentifier");

            // Foreign keys
            HasOptional(a => a.FileMange).WithMany(b => b.FileModulars).HasForeignKey(c => c.RefFIleID); // FileMange_FileModular_FileID
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
