// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Tmp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Tmp.Data.Entity
{
    // GanttTask
    public partial class GanttTask: BaseEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public string TaskText { get; set; } // TaskText
        public DateTime StartDate { get; set; } // StartDate
        public int Duration { get; set; } // Duration
        public double Progress { get; set; } // Progress
        public int? ParentId { get; set; } // ParentId
        public string TaskType { get; set; } // TaskType
        
        public GanttTask()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
