// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Tmp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Tmp.Data.Entity
{
    // GanttTask
    public partial class GanttTaskConfiguration : EntityTypeConfiguration<GanttTask>
    {
        public GanttTaskConfiguration()
            : this("dbo")
        {
        }
 
        public GanttTaskConfiguration(string schema)
        {
            ToTable(schema + ".GanttTask");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName("Id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.TaskText).HasColumnName("TaskText").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.StartDate).HasColumnName("StartDate").IsRequired().HasColumnType("date");
            Property(x => x.Duration).HasColumnName("Duration").IsRequired().HasColumnType("int");
            Property(x => x.Progress).HasColumnName("Progress").IsRequired().HasColumnType("float");
            Property(x => x.ParentId).HasColumnName("ParentId").IsOptional().HasColumnType("int");
            Property(x => x.TaskType).HasColumnName("TaskType").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
