// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Tmp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Tmp.Data.Entity
{
    public interface IMyDbContext : IDisposable
    {
        DbSet<Account> Accounts { get; set; } // tbLOG_Account
        DbSet<AccountOfRoles> AccountOfRoles { get; set; } // tbLOG_AccountOfRoles
        DbSet<BuildingModel> BuildingModels { get; set; } // BuildingModel
        DbSet<CodeTable> CodeTables { get; set; } // tbCOM_CodeTable
        DbSet<Departments> Departments { get; set; } // tbLOG_Departments
        DbSet<ErrorInfo> ErrorInfoes { get; set; } // tbLOG_ErrorInfo
        DbSet<FileMange> FileManges { get; set; } // FileMange
        DbSet<FileModular> FileModulars { get; set; } // FileModular
        DbSet<GanttLink> GanttLinks { get; set; } // GanttLink
        DbSet<GanttTask> GanttTasks { get; set; } // GanttTask
        DbSet<Menus> Menus { get; set; } // tbLOG_Menus
        DbSet<ModelInfo> ModelInfoes { get; set; } // ModelInfo
        DbSet<Permission> Permissions { get; set; } // tbLOG_Permission
        DbSet<ProjectInfo> ProjectInfoes { get; set; } // ProjectInfo
        DbSet<Roles> Roles { get; set; } // tbLOG_Roles
        DbSet<Schedule> Schedules { get; set; } // Schedule
        DbSet<sysdiagrams> sysdiagrams { get; set; } // sysdiagrams
        DbSet<VersionControl> VersionControls { get; set; } // tbCOM_VersionControl

        int SaveChanges();
        
        // Stored Procedures
    }

}
// </auto-generated>
