// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.0
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using Tmp.Core.Data;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Tmp.Data.Entity
{
    // MaterialInfo
    public partial class MaterialInfoConfiguration : EntityTypeConfiguration<MaterialInfo>
    {
        public MaterialInfoConfiguration()
            : this("dbo")
        {
        }
 
        public MaterialInfoConfiguration(string schema)
        {
            ToTable(schema + ".MaterialInfo");
            HasKey(x => x.tbid);

            Property(x => x.tbid).HasColumnName("tb_id").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.tbnamebefore).HasColumnName("tb_name_before").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.tbnamenow).HasColumnName("tb_name_now").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.tbdate).HasColumnName("tb_date").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.tbsize).HasColumnName("tb_size").IsOptional().HasColumnType("decimal");
            Property(x => x.tbusername).HasColumnName("tb_username").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.tbuserid).HasColumnName("tb_userid").IsOptional().HasColumnType("int");
            Property(x => x.tbtype).HasColumnName("tb_type").IsOptional().HasColumnType("int");
            Property(x => x.tbaddress).HasColumnName("tb_address").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.tbprojectid).HasColumnName("tb_projectid").IsOptional().HasColumnType("int");
            Property(x => x.tbproject).HasColumnName("tb_project").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.tbproject).HasColumnName("tb_fileType").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.tbproject).HasColumnName("tb_fileExplain").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
